var quizContent = [
  {
    question: "Where would you find the Empire State building?",
    type: "single",
    options: ["New York", "Los Angeles", "San Francisco", "New Orleans"],
    correctFeedback: "That’s right.",
    incorrectFeedback: "That’s not it.",
    correctAnswer: "New York",
    seen: 0,
  },
  {
    question: "Identify the components of a PC",
    type: "multiple",
    options: ["Processor", "Memory", "Hard Disk", "CD-ROM Drive", "Printer"],
    correctAnswer: ["Processor", "Memory", "Hard Disk", "CD-ROM Drive"],
    correctFeedback: "That’s right.",
    incorrectFeedback: "That’s not it.",
    partlyCorrectFeedback: "Your partly right",
    seen: 0,
  },
  {
    question: "_______ is a character in the film 'The Matrix'",
    type: "input",
    options: ["R2D2", "Neo", "Ripley"],
    correctFeedback: "That’s right.",
    incorrectFeedback: "That’s not it.",
    correctAnswer: "Neo",
    seen: 0,
  },
];
